# Generated by Django 4.2.6 on 2023-10-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
